name: Lobby
author: Teeage
version: ${project.version}
main: de.heliosdevelopment.helioslobby.Lobby
softdepend: [HeliosCore, heliosperms, HeliosPoints, Vault]
commands:
  clearchat:
  clear:
  gm:
  remove:
  set:
  vanish:
  spawnwitch:
  despawnwitch:
  keys:
  points: