name: HeliosLobby
author: Teeage
version: 1.0
main: de.heliosdevelopment.helioslobby.Lobby
website: teeage.de
softdepend: [HeliosCore]
commands:
  clearchat:
  clear:
  gm:
  remove:
  set:
  vanish:               

         
   
    
