name: Lobby
author: EinfachNurTommm
version: 1.2.1
main: de.heliosdevelopment.helioslobby.Lobby
softdepend: [Vault]
commands:
  clearchat:
  clear:
  gm:
  remove:
  set:
  vanish:
  spawnwitch:
  despawnwitch:
  keys:
  points: